service: hubspot-webhook-handler

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${{opt:stage, 'dev'}}
  maximumRetryAttempts: 0
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
      Resource: "*"

functions:
  hubspot_webhook_handler:
    name: hubspot-webhook-handler
    handler: handler.lambda_handler
    timeout: 900
    memorySize: 128
    layers:
      - arn:aws:lambda:us-east-1:630977122946:layer:python-deps-layer:1
    package:
      patterns:
        - '!archive/**'
        - '!__pycache__/**'
        - '!**/*.pyc'

package:
  individually: true

