service: hs-deal-contact-associations

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${{opt:stage, 'dev'}}
  maximumRetryAttempts: 0
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"

functions:
  hs_deal_contact_associations:
    name: hs-deal-contact-associations
    handler: handler.lambda_handler
    timeout: 160
    memorySize: 128
    package:
      patterns:
        - '!**'
        - 'handler.py'
        - 'supporting_functions.py'
        - 'object_properties.json'
        - 'src/**'
        - '!**/*tests*/**'
        - '!.pytest_cache/**'
        - '!**/__pycache__/**'
        - '!**/*.pyc'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
    useDownloadCache: true
    useStaticCache: true

package:
  individually: true
